name: Publish to NPM and GPR

on:
    release:
        types: [created]

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            redis:
                image: redis
                ports:
                    - 6379:6379
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'npm'
            - run: npm ci
            - run: npm test
            - run: npm run build
            - name: Archive Production Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: production-artifacts
                  path: dist

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  name: production-artifacts
                  path: dist
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'npm'
            - name: Configure npm for public registry
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
            - run: npm publish --access public

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  name: production-artifacts
                  path: dist
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@devhuset-oss'
                  cache: 'npm'
            - name: Configure npm for GitHub Packages
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
                  echo "@devhuset-oss:registry=https://npm.pkg.github.com/" >> .npmrc
            - run: npm publish
